
version: "3.7"

services:
  django_web:
    build: .
    command: >
      ash -c "python manage.py migrate && gunicorn mak.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static:/app/static
      - media:/app/media
      - .:/app/
    env_file:
      - ./.env
    depends_on:
      - postgres_db
    networks:
      - db_net
      - ng_net
  postgres_db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=amir_mak
      - POSTGRES_PASSWORD=162534
      - POSTGRES_DB=roadmap
    networks:
      - db_net
  nginx:
    build: ./nginx
    volumes:
      - static:/app/static
      - media:/app/media
    ports:
      - 8008:80
    depends_on:
      - django_web
    networks:
      - ng_net
  redis:
    image: redis:alpine
    volumes:
      - redis_val:/data
    networks:
      - db_net
  celery:
    image: mak_django_web
    restart: always
    # build:
    #   context: .
#      dockerfile: dokckerfile-name-alternative
#      args:
#        name : ashkan
    command: >
      ash -c "touch celery.log  && celery -A mak worker -l info &> celery.log"
    volumes:
      - .:/app
    depends_on:
      - django_web
      - redis
    networks:
      - db_net
volumes:
  postgres_data:
  static:
  media:
  redis_val:

networks:
  db_net:
  ng_net: