# Generated by Django 4.0 on 2022-01-09 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salesman_profile', '0001_initial'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='salesman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salesman_profile.salesmanprofile'),
        ),
        migrations.AddField(
            model_name='categoryproduct',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.categoryproduct'),
        ),
    ]
