# Generated by Django 3.2.9 on 2021-12-26 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesman_profile', '0007_auto_20211226_0714'),
        ('product', '0003_auto_20211225_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='title',
        ),
        migrations.AddField(
            model_name='product',
            name='salesman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salesman_profile.salesmanprofile'),
        ),
    ]
