# Generated by Django 3.2.9 on 2021-12-26 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='salesman',
        ),
    ]
