# Generated by Django 3.2.9 on 2021-12-26 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesman_profile', '0009_remove_salesmanproduct_product'),
        ('product', '0006_remove_product_salesman'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='salesman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salesman_profile.salesmanprofile'),
        ),
    ]
