# Generated by Django 4.0.1 on 2022-01-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_product_slug_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sold_out_num',
            field=models.BigIntegerField(blank=True, default=0),
        ),
    ]
