# Generated by Django 3.2.9 on 2022-01-08 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_sold_out_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryproduct',
            name='img',
            field=models.ImageField(null=True, upload_to='static/img'),
        ),
    ]
