# Generated by Django 3.2.9 on 2022-01-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_categoryproduct_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryproduct',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/img'),
        ),
    ]
