# Generated by Django 4.0.1 on 2022-01-10 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_product_slug_alter_product_salesman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='salesman',
        ),
    ]
