# Generated by Django 3.2.9 on 2022-01-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_categoryproduct_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sold_out_num',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
