# Generated by Django 3.2.9 on 2021-12-26 08:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0007_product_salesman'),
        ('salesman_profile', '0010_delete_salesmanproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesmanProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True)),
                ('date_import_product', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_last_update', models.DateTimeField(auto_now=True, null=True)),
                ('count', models.BigIntegerField(null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.product')),
                ('salesman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salesman_profile.salesmanprofile')),
            ],
        ),
    ]
