# Generated by Django 4.0 on 2022-01-31 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmanproduct',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
