# Generated by Django 3.2.9 on 2021-12-26 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_property'),
        ('supply', '0002_auto_20211226_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmanproduct',
            name='prop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.property'),
        ),
        migrations.AddField(
            model_name='salesmanproduct',
            name='value',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='SalesManProperty',
        ),
    ]
