# Generated by Django 3.2.9 on 2021-12-26 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0004_auto_20211226_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesmanproperty',
            old_name='product',
            new_name='salesman',
        ),
    ]
