# Generated by Django 4.0 on 2022-01-11 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesman_profile', '0011_remove_salesmanaddress_seller_id_and_more'),
        ('product', '0013_rename_img_product_img1_remove_product_salesman_and_more'),
        ('supply', '0005_rename_product_salesmanproperty_salesman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmanproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='product.product'),
        ),
        migrations.AlterField(
            model_name='salesmanproduct',
            name='salesman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesmans', to='salesman_profile.salesmanprofile'),
        ),
        migrations.AlterField(
            model_name='salesmanproperty',
            name='prop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='props', to='product.property'),
        ),
        migrations.AlterField(
            model_name='salesmanproperty',
            name='salesman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesproducts', to='supply.salesmanproduct'),
        ),
    ]
