# Generated by Django 4.0.1 on 2022-01-10 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_rename_img_product_img1_product_img2_product_img3_and_more'),
        ('supply', '0006_alter_salesmanproduct_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmanproperty',
            name='prop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='props', to='product.property'),
        ),
        migrations.AlterField(
            model_name='salesmanproperty',
            name='salesman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesmans', to='supply.salesmanproduct'),
        ),
    ]
