# Generated by Django 4.0.1 on 2022-01-10 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0007_alter_salesmanproperty_prop_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmanproperty',
            name='salesman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesproducts', to='supply.salesmanproduct'),
        ),
    ]
