# Generated by Django 4.0 on 2021-12-23 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salesman_profile', '0002_delete_historysalesman'),
        ('customer_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order', models.JSONField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='customer_profile.customerprofile')),
                ('salesman', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='salesman_profile.salesmanprofile')),
            ],
        ),
    ]
