# Generated by Django 3.2.9 on 2021-12-26 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='order',
            new_name='cart',
        ),
    ]
