# Generated by Django 4.0 on 2022-01-12 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
        ('customer_profile', '0002_initial'),
        ('salesman_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='customer_payment', to='customer_profile.customerprofile'),
        ),
        migrations.AddField(
            model_name='payment',
            name='salesman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='salesman_payment', to='salesman_profile.salesmanprofile'),
        ),
    ]
