# Generated by Django 4.0.1 on 2022-01-11 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesman_profile', '0011_remove_salesmanaddress_seller_id_and_more'),
        ('customer_profile', '0004_alter_customeraddress_customer_and_more'),
        ('payment', '0002_rename_order_payment_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cusomer_payment', to='customer_profile.customerprofile'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='salesman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='salesman_payment', to='salesman_profile.salesmanprofile'),
        ),
    ]
