# Generated by Django 4.0 on 2021-12-23 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesman_profile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistorySalesman',
        ),
    ]
