# Generated by Django 4.0 on 2022-01-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesman_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
    ]
