# Generated by Django 4.0 on 2022-01-09 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesman_profile', '0002_remove_user_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesmanprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='salesmanprofile',
            name='telephone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
