# Generated by Django 4.0 on 2021-12-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesman_profile', '0002_delete_historysalesman'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmanprofile',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
