# Generated by Django 3.2.9 on 2021-12-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_sub_category_categoryproduct_parent_and_more'),
        ('salesman_profile', '0003_salesmanprofile_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesmanprofile',
            name='count',
        ),
        migrations.AddField(
            model_name='salesmanproduct',
            name='count',
            field=models.BigIntegerField(null=True),
        ),
        # migrations.AlterField(
        #     model_name='salesmanprofile',
        #     name='Product',
        #     # field=models.ManyToManyField(through='salesman_profile.SalesmanProduct', to='product.Product'),

        # ),

        migrations.RemoveField(
            model_name='salesmanprofile',
            name='Product',
                ),

        migrations.AddField(
            model_name='salesmanprofile',
            name='Product',
            field=models.ManyToManyField(through='salesman_profile.SalesmanProduct', to='product.Product'),
        ),
    ]
