# Generated by Django 3.2.9 on 2021-12-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salesman_profile', '0004_auto_20211225_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesmanprofile',
            name='price',
        ),
        migrations.AddField(
            model_name='salesmanproduct',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
