# Generated by Django 3.2.9 on 2021-12-25 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesman_profile', '0005_auto_20211225_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesmanprofile',
            name='Product',
        ),
    ]
