# Generated by Django 3.2.9 on 2021-12-26 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesman_profile', '0006_remove_salesmanprofile_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesmanproduct',
            name='product',
        ),
        migrations.AlterField(
            model_name='salesmanproduct',
            name='date_import_product',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesmanproduct',
            name='date_last_update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesmanproduct',
            name='salesman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salesman_profile.salesmanprofile'),
        ),
    ]
