# Generated by Django 3.2.9 on 2021-12-26 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_remove_product_salesman'),
        ('salesman_profile', '0007_auto_20211226_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesmanproduct',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='product.product'),
        ),
    ]
