# Generated by Django 3.2.9 on 2021-12-26 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesman_profile', '0008_salesmanproduct_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesmanproduct',
            name='product',
        ),
    ]
