# Generated by Django 3.2.9 on 2021-12-26 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salesman_profile', '0009_remove_salesmanproduct_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SalesmanProduct',
        ),
    ]
