# Generated by Django 4.0.1 on 2022-01-11 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('salesman_profile', '0010_delete_salesmanproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesmanaddress',
            name='seller_id',
        ),
        migrations.AddField(
            model_name='salesmanaddress',
            name='salesman_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salesman_ad', to='salesman_profile.salesmanprofile'),
        ),
    ]
