# Generated by Django 4.0 on 2022-01-12 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(null=True)),
                ('is_paid', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryCustomer',
            fields=[
                ('cart_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cart.cart')),
            ],
            bases=('cart.cart',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('cart_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cart.cart')),
                ('date_order', models.DateTimeField(auto_now_add=True, null=True)),
                ('expire_date', models.DateTimeField(auto_now=True, null=True)),
            ],
            bases=('cart.cart',),
        ),
    ]
