# Generated by Django 4.0 on 2021-12-18 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_order', models.DateTimeField(auto_now_add=True)),
                ('expire_date', models.DateTimeField(auto_now=True)),
                ('count_order', models.BigIntegerField()),
                ('is_paid', models.BooleanField(default=False)),
            ],
        ),
    ]
