# Generated by Django 3.2.9 on 2021-12-26 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_profile', '0002_rename_seller_id_customeraddress_customer'),
        ('product', '0007_product_salesman'),
        ('salesman_profile', '0010_delete_salesmanproduct'),
        ('cart', '0008_auto_20211226_0837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='count_order',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order',
            name='salesman',
        ),
        migrations.AddField(
            model_name='cart',
            name='count_order',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='customer_profile.customerprofile'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product'),
        ),
        migrations.AddField(
            model_name='cart',
            name='salesman',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='salesman_profile.salesmanprofile'),
        ),
        migrations.AddField(
            model_name='order',
            name='cart_ptr',
            field=models.OneToOneField(auto_created=True, default=123, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cart.cart'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='is_paid',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_order',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='expire_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
