# Generated by Django 3.2.9 on 2022-01-08 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_historycustomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='salesman',
        ),
    ]
