# Generated by Django 4.0.1 on 2022-01-09 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_historycustomer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='salesman',
        ),
    ]
