# Generated by Django 3.2.9 on 2022-01-08 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_remove_cart_salesman'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='count_order',
        ),
    ]
