# Generated by Django 4.0 on 2022-01-11 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_rename_img_product_img1_remove_product_salesman_and_more'),
        ('customer_profile', '0005_alter_customeraddress_customer_and_more'),
        ('cart', '0013_remove_cart_count_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_customers', to='customer_profile.customerprofile'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_products', to='product.product'),
        ),
    ]
