# Generated by Django 3.2.9 on 2021-12-25 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraddress',
            old_name='seller_id',
            new_name='customer',
        ),
    ]
