# Generated by Django 3.2.9 on 2021-12-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_profile', '0002_rename_seller_id_customeraddress_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoryCustomer',
        ),
    ]
