# Generated by Django 4.0.1 on 2022-01-11 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_categoryproduct_parent_alter_product_cat_and_more'),
        ('customer_profile', '0003_delete_historycustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_ad', to='customer_profile.customerprofile'),
        ),
        migrations.AlterField(
            model_name='favotite',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_fav', to='product.product'),
        ),
        migrations.AlterField(
            model_name='favotite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='customer_profile.customerprofile'),
        ),
    ]
