# Generated by Django 3.2.9 on 2022-01-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_profile', '0003_delete_historycustomer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='telephone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
