# Generated by Django 4.0 on 2022-01-11 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_rename_img_product_img1_remove_product_salesman_and_more'),
        ('customer_profile', '0004_auto_20220108_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_ad', to='customer_profile.customerprofile'),
        ),
        migrations.AlterField(
            model_name='favotite',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_fav', to='product.product'),
        ),
        migrations.AlterField(
            model_name='favotite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='customer_profile.customerprofile'),
        ),
    ]
