# Generated by Django 3.2.9 on 2021-12-25 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='userseller',
        ),
    ]
