# Generated by Django 3.2.9 on 2021-12-25 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_remove_comment_userseller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='usercustomer',
            new_name='customer',
        ),
    ]
