# Generated by Django 4.0.1 on 2022-01-11 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_profile', '0004_alter_customeraddress_customer_and_more'),
        ('product', '0013_alter_categoryproduct_parent_alter_product_cat_and_more'),
        ('comment', '0005_rename_usercustomer_comment_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='customer_profile.customerprofile'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comment', to='product.product'),
        ),
    ]
